import { Node, Edge } from 'reactflow';

export function generateMoveCode(nodes: Node[], edges: Edge[]): string {
  if (nodes.length === 0) {
    return `// 🔧 Drag blocks onto the canvas to start building your ZK circuit\n// Generated Move code will appear here in real-time\n\nmodule endless::zk_circuit {\n    // Your circuit logic will be generated here\n}`;
  }

  const blockTypes = nodes.map(n => n.data.blockType as string);
  const hasHash = blockTypes.includes('hash');
  const hasSig = blockTypes.includes('signature');
  const hasRange = blockTypes.includes('range_proof');
  const hasMerkle = blockTypes.includes('merkle_proof');
  const hasEquality = blockTypes.includes('equality');
  const hasAnd = blockTypes.includes('and_gate');
  const publicInputs = nodes.filter(n => n.data.blockType === 'public_input');
  const privateInputs = nodes.filter(n => n.data.blockType === 'private_input');
  const outputs = nodes.filter(n => n.data.blockType === 'output');

  let code = `module endless::zk_circuit {
    use std::vector;
    use std::hash;
    use endless_std::crypto;
    use endless_framework::zk_proof;

    /// ZK Circuit: Auto-generated by Move ZK Circuit Builder
    /// Blocks: ${nodes.length} | Connections: ${edges.length}
    
    /// ══════════════════════════════════════════
    /// CIRCUIT STRUCT
    /// ══════════════════════════════════════════
    struct CircuitProof has drop, store {
${privateInputs.map((n, i) => `        witness_${i}: vector<u8>,  // ${n.data.label || 'private input'}`).join('\n')}
${publicInputs.map((n, i) => `        public_${i}: vector<u8>,   // ${n.data.label || 'public input'}`).join('\n')}
    }

    /// ══════════════════════════════════════════
    /// VERIFICATION ENTRY FUNCTION
    /// ══════════════════════════════════════════
    public entry fun verify_proof(
        account: &signer,
${privateInputs.map((n, i) => `        witness_${i}: vector<u8>,`).join('\n')}
${publicInputs.map((n, i) => `        public_${i}: vector<u8>,`).join('\n')}
    ) {`;

  if (hasHash) {
    code += `
        // ── Hash Computation ──
        let computed_hash = hash::sha2_256(witness_0);`;
  }

  if (hasSig) {
    code += `
        // ── Signature Verification ──
        let sig_valid = crypto::ed25519_verify(
            &witness_1,  // signature
            &public_0,   // public key
            &witness_0   // message
        );
        assert!(sig_valid, 0x1001); // E_INVALID_SIGNATURE`;
  }

  if (hasRange) {
    code += `
        // ── Range Proof ──
        let value = zk_proof::bytes_to_u64(&witness_0);
        let min_val = 0u64;
        let max_val = 1000000u64;
        assert!(value >= min_val && value <= max_val, 0x1002); // E_OUT_OF_RANGE`;
  }

  if (hasMerkle) {
    code += `
        // ── Merkle Membership Proof ──
        let leaf_hash = hash::sha2_256(witness_0);
        let is_member = zk_proof::verify_merkle_proof(
            &leaf_hash,
            &public_0,     // merkle root
            &witness_1     // proof path
        );
        assert!(is_member, 0x1003); // E_NOT_IN_TREE`;
  }

  if (hasEquality) {
    code += `
        // ── Equality Assertion ──
        assert!(computed_hash == public_0, 0x1004); // E_HASH_MISMATCH`;
  }

  if (hasAnd) {
    code += `
        // ── Combined Assertion (AND) ──
        // All previous assertions must pass for proof to be valid`;
  }

  if (outputs.length > 0) {
    code += `

        // ── Emit Verification Event ──
        zk_proof::emit_verification_success(account);`;
  }

  code += `
    }

    /// ══════════════════════════════════════════
    /// FRONTEND INTEGRATION (Luffa Mini-App)
    /// ══════════════════════════════════════════
    /// 
    /// \`\`\`typescript
    /// import { EndlessClient } from "@endless-labs/ts-sdk";
    /// 
    /// const client = new EndlessClient({ network: "testnet" });
    /// 
    /// async function verifyZKProof() {
    ///     const tx = await client.submitTransaction({
    ///         function: "endless::zk_circuit::verify_proof",
    ///         arguments: [
${privateInputs.map((_, i) => `    ///             witnessData${i},`).join('\n')}
${publicInputs.map((_, i) => `    ///             publicInput${i},`).join('\n')}
    ///         ],
    ///     });
    ///     console.log("Proof verified:", tx.hash);
    /// }
    /// \`\`\`
}`;

  return code;
}

export function generateExportPackage(moveCode: string): string {
  return `# Move ZK Circuit - Export Package
# Generated by Move ZK Circuit Builder for Endless

## Move.toml
\`\`\`toml
[package]
name = "ZKCircuit"
version = "1.0.0"

[dependencies]
EndlessFramework = { git = "https://github.com/endless-labs/endless-framework.git", rev = "main" }

[addresses]
endless = "0x1"
\`\`\`

## sources/zk_circuit.move
\`\`\`move
${moveCode}
\`\`\`

## Deploy Instructions
1. Install Endless CLI: \`curl -fsSL https://endless.dev/install | bash\`
2. Initialize project: \`endless init\`  
3. Compile: \`endless move compile\`
4. Test: \`endless move test\`
5. Deploy: \`endless move publish --network testnet\`
`;
}
